# Generated by Django 5.0.2 on 2024-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('skills', models.CharField(max_length=128, null=True)),
                ('experience', models.CharField(max_length=128, null=True)),
                ('education', models.CharField(max_length=128, null=True)),
                ('fullname', models.CharField(max_length=128, null=True)),
                ('titre', models.CharField(max_length=128, null=True)),
                ('create_at', models.BooleanField(default=False)),
                ('update_at', models.BooleanField(default=False)),
                ('create_by', models.BooleanField(default=False)),
                ('update_by', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
